include ./make/help.mk
include ./make/release.mk

.PHONY: all
all: test release ## Test, (build) and release. Ready to deploy.

.PHONY: build
build: ## Create all build artifacts
	npm install
	npm audit fix
	npm run build

.PHONY: clean
clean: ## Remove all build artifacts
	-@rm public/build/* 2>/dev/null || true

.PHONY: deploy
deploy: ## Deploy latest release
	surge public https://memorablewords.surge.sh

.PHONY: release
release: CURRENT_RELEASE = $$((${RELEASE} + 1))
release: ## Create a release
	@echo "RELEASE = ${CURRENT_RELEASE}" > ./make/release.mk
	make src/version.js build

.PHONY: record-release
record-release: CURRENT_RELEASE = $$((${RELEASE} + 1))
record-release: ## Commit a release to version control
	@git add make/release.mk src/version.js \
	&& git commit -m "Add release #${CURRENT_RELEASE}" \
	&& git tag -a "release-${CURRENT_RELEASE}" -m "Release #${RECURRENT_RELEASELEASE}"

.PHONY: src/version.js # ensure the version is always fresh
src/version.js:
	@echo "// File generated by release script, DO NOT EDIT.\nexport const version = '${RELEASE}–$(shell git log -1 --oneline | cut -d' ' -f1)';" > src/version.js

.PHONY: test
test: ## Run package tests
	npm test
